// <auto-generated />
namespace InfraMap.Infraestrutura.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MapeamentoMaquinaMesaUsuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MapeamentoMaquinaMesaUsuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201604181703269_MapeamentoMaquinaMesaUsuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
