// <auto-generated />
namespace InfraMap.Infraestrutura.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adicionadocolunasparamemoriaramnamaquina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionadocolunasparamemoriaramnamaquina));
        
        string IMigrationMetadata.Id
        {
            get { return "201606032045203_Adicionado colunas para memoria ram na maquina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
