//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraMap.Infra.Ef.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Andar
    {
        public Andar()
        {
            this.Mesa = new HashSet<Mesa>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int Sede_Id { get; set; }
    
        public virtual Sede Sede { get; set; }
        public virtual ICollection<Mesa> Mesa { get; set; }
    }
}
