//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraMap.Infra.Ef.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        public Colaborador()
        {
            this.Mesa = new HashSet<Mesa>();
        }
    
        public int Id { get; set; }
        public int Gerente_Id { get; set; }
        public int Usuario_Id { get; set; }
    
        public virtual Gerente Gerente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Mesa> Mesa { get; set; }
    }
}
