//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraMap.Infra.Ef.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        public int Id { get; set; }
        public int Andar_Id { get; set; }
        public Nullable<int> Colaborador_Id { get; set; }
        public Nullable<int> Maquina_Id { get; set; }
        public Nullable<int> Ramal_Id { get; set; }
    
        public virtual Andar Andar { get; set; }
        public virtual Colaborador Colaborador { get; set; }
        public virtual Maquina Maquina { get; set; }
        public virtual Ramal Ramal { get; set; }
    }
}
