//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraMap.Infra.Ef.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfraMapDbEntitiesModel : DbContext
    {
        public InfraMapDbEntitiesModel()
            : base("name=InfraMapDbEntitiesModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Andar> Andar { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<Gerente> Gerente { get; set; }
        public virtual DbSet<Maquina> Maquina { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Permissao> Permissao { get; set; }
        public virtual DbSet<Ramal> Ramal { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
