//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraMap.Infra.Ef.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        public Sede()
        {
            this.Andar = new HashSet<Andar>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string NomeCidade { get; set; }
    
        public virtual ICollection<Andar> Andar { get; set; }
    }
}
