//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraMap.Infra.Ef.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Colaborador = new HashSet<Colaborador>();
            this.Gerente = new HashSet<Gerente>();
            this.Permissao = new HashSet<Permissao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<Colaborador> Colaborador { get; set; }
        public virtual ICollection<Gerente> Gerente { get; set; }
        public virtual ICollection<Permissao> Permissao { get; set; }
    }
}
